[package]
name = "rust_rise"
version = "0.1.0"
edition = "2021"
authors =["binayak bhattarai<binayakbhattarai268@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
